baseURL: https://varisportfolio.netlify.app/
languageCode: en-us
title: Forty
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Know more about me
    subtitle: |-
      Passionate about investing in equities and alternative assets.
      Please feel free to contact me via Linkedin icon at the end of this page.
    title: Varis Sinthopruangchai's Interactive Profile
  blog: {}
  contact:
    address:
      - city: London  
        country: UK 
        street: 
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: variss.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: 447389811956
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/varis38653965
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/bright.varis
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/bright_vs/
      - icon: fa-github
        label: GitHub
        url: https://github.com/Varismfa
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/varis-sinthopruangchai-5736b9105/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: 
    title: Varis Sinthopruangchai
  tiles:
    enable: yes
    showcase:
      - image: CV_cover2.jpg
        subtitle: Updated on 19 October 2021
        title: My Personal CV
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: Volunteer / Piano / Traveling
        title: Extracurricular Activities
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Interest rate / R Markdown
        title: Macroeconomic Analysis 
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Covid-19 impact on gold price presentation
        title: Gold Analysis 
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Logitech / Microsoft 
        title: Stock Analysis Report 
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Return/ CAPM / Minimum Variance Portfolio 
        title: Interactive Stock Portfolio 
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "1.Macroeconomic Analysis (gold and interest rate) 2. Portfolio allocation (Minimum Variance Portfolio and optimal portfolio optimization 3. Fundamental Research on stock)  "
    title: My Three Main Interests in Asset Management Field 
    url: blogs
