baseURL: https://varisportfolio.netlify.app/
languageCode: en-us
title: Forty
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Know more about me
    subtitle: |-
      Passionate about investing in equities and alternative assets.
      Please feel free to contact me via Linkedin icon at the end of this page.
    title: Varis Sinthopruangchai's Interactive Profile
    image: Interest Rate.jpg
  blog: {}
  contact:
    address:
      - city: London  
        country: UK 
        street: 
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: variss.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: 447389811956
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Varis Sinthopruangchai
    enable: yes
    quicklinks:
      - alt: Download
        text: 'CV'
        url: https://drive.google.com/file/d/1H1YHr29w44YN95eezMwXVe4ICCwTpV8u/view?usp=sharing
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/varis38653965
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/bright.varis
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/bright_vs/
      - icon: fa-github
        label: GitHub
        url: https://github.com/Varismfa
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/varis-sinthopruangchai-5736b9105/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Explore my Stories
        url: blogs
    button2:
      - name: Interactive stock Portfolio
        url: https://varissinthopruangchai.shinyapps.io/my_websites/
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Personal CV
        url: blogs/aliquam
      - name: Extracurricular Activities
        url: blogs/tempus
      - name: Macroeconomic Analysis
        url: blogs/magna
      - name: Gold Analysis
        url: blogs/ipsum
      - name: Stock Analysis Report
        url: blogs/stock
    menu: Menu
    subtitle: 
    title: Varis Sinthopruangchai
  tiles:
    enable: yes
    showcase:
      - image: CV_cover4.jpg
        subtitle: Updated on 19 October 2021
        title: My Personal CV
        url: blogs/aliquam
      - image: Volunteer.jpg
        subtitle: Volunteer
        title: Extracurricular Activities
        url: blogs/tempus
      - image: Interest Rate.jpg
        subtitle: Interest rate / R Markdown
        title: Macroeconomic Analysis 
        url: blogs/magna
      - image: gold.jpg
        subtitle: Covid-19 impact on gold price presentation
        title: Gold Analysis 
        url: blogs/ipsum
      - image: analysis.jpg
        subtitle: Logitech / Microsoft 
        title: Stock Analysis Report 
        url: blogs/stock
      - image: portfolio.jpg
        subtitle: Return/ CAPM / Minimum Variance Portfolio 
        title: Interactive Stock Portfolio 
        url: blogs/portfolio
  two:
    buttonText: Explore my Stories
    enable: yes
    subtitle: "My name is Varis Sinthopruangchai from Bangkok, Thailand. Currently, I am studying at London Business School for my Masters Degree.I have been interest in the 3 main areas of asset management: 1. Gold Analysis 2. Porfolio Allocation 3.Stock Analysis"
    title: Brief Introduction
    url: blogs
